Webapi/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Webapi.Models;
using Webapi.Repositorio.IRepositorio;
using Webapi.Views;
using Webapi.Views.Utilidades;

namespace Webapi.Controllers
{
    [Authorize]
    public class CategoriasController : Controller
    {
        private readonly ICategoriaRepositorio _repoCategoria;

        public CategoriasController(ICategoriaRepositorio repoCategoria)
        {
            _repoCategoria = repoCategoria;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View(new Categoria() { });
        }

        [HttpGet]
        public async Task<IActionResult> GetTodasCategorias()
        {
            return Json(new { data = await _repoCategoria.GetTodoAsync(CT.RutaCategoriasApi) });
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _repoCategoria.CrearAsync(CT.RutaCategoriasApi, categoria, HttpContext.Session.GetString("JWToken"));
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            Categoria itemCategoria = new Categoria();
            if (id == null)
            {
                return NotFound();
            }
            itemCategoria = await _repoCategoria.GetAsync(CT.RutaCategoriasApi, id.GetValueOrDefault());
            if (itemCategoria == null)
            {
                return NotFound();
            }
            return View(itemCategoria);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                await _repoCategoria.ActualizarAsync(CT.RutaCategoriasApi + categoria.Id, categoria, HttpContext.Session.GetString("JWToken"));
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _repoCategoria.BorrarAsync(CT.RutaCategoriasApi, id, HttpContext.Session.GetString("JWToken"));
            if (status)
            {
                return Json(new { success = true, message = "Borrado Correctamente" });
            }
            return Json(new { success = false, message = "Borrado Corretamente" });
        }
    }
}

Webapi/Controllers/PeliculasController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using Webapi.Models;
using Webapi.Models.ViewModels;
using Webapi.Repositorio.IRepositorio;
using Webapi.Controllers;
using Webapi.Views.Utilidades;
using Microsoft.AspNetCore.Authorization;

namespace Webapi.Controllers
{
     [Authorize]
    public class PeliculasController : Controller
    {
        private readonly IPeliculasRepositorio _repoPeliculas;
        private readonly ICategoriaRepositorio _repoCategoria;

        public PeliculasController(IPeliculasRepositorio repoPeliculas, ICategoriaRepositorio repoCategoria)
        {
            _repoPeliculas = repoPeliculas;
            _repoCategoria = repoCategoria;

        }
        [HttpGet]
        public IActionResult Index()
        {
            return View(new Pelicula() { });
        }
        // [HttpGet]
        // public async Task<IActionResult> GetTodoPeliculas()
        // {
        //     return Json(new { data = await _repoPeliculas.GetPeliculasTodoAsync(CT.RutaPeliculasApi) });
        // }
        [HttpGet]
        public async Task<IActionResult> GetTodoPeliculas()
        {
            var resultado = await _repoPeliculas.GetPeliculasTodoAsync(CT.RutaPeliculasApi);
            return Json(new { data = resultado.Items });
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            IEnumerable<Categoria> ctList = (IEnumerable<Categoria>)await _repoCategoria.GetTodoAsync(CT.RutaCategoriasApi);
            PeliculasVM objVM = new PeliculasVM()
            {
                ListaCategorias = ctList.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()

                }),
                Pelicula = new Pelicula()
            };
            return View(objVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Pelicula pelicula)
        {
            IEnumerable<Categoria> ctList = (IEnumerable<Categoria>)
            await _repoCategoria.GetTodoAsync(CT.RutaCategoriasApi);

            PeliculasVM objVM = new PeliculasVM()
            {
                ListaCategorias = ctList.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()

                }),
                Pelicula = new Pelicula()
            };
            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {

                    pelicula.Imagen = files[0];//Asignar el InforFile directamente
                }
                else
                {
                    return View(objVM);
                }
                await _repoPeliculas.CrearPeliculaAsync(CT.RutaPeliculasApi, pelicula, HttpContext.Session.GetString("JWToken"));
                return RedirectToAction(nameof(Index));
            }
            return View(objVM);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            IEnumerable<Categoria> ctList = (IEnumerable<Categoria>)await _repoCategoria.GetTodoAsync(CT.RutaCategoriasApi);
            PeliculasVM objVM = new PeliculasVM()
            {
                ListaCategorias = ctList.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()

                }),
                Pelicula = new Pelicula()
            };
            if (id == null)
            {
                return NotFound();
            }
            //para mostrar los datos  en el formulario Edit
            objVM.Pelicula = await _repoPeliculas.GetAsync(CT.RutaPeliculasApi, id.GetValueOrDefault());
            if (objVM.Pelicula == null)
            {
                return NotFound();
            }
            return View(objVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Pelicula pelicula)
        {
            IEnumerable<Categoria> ctList = (IEnumerable<Categoria>)
            await _repoCategoria.GetTodoAsync(CT.RutaCategoriasApi);

            PeliculasVM objVM = new PeliculasVM()
            {
                ListaCategorias = ctList.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()

                }),
                Pelicula = new Pelicula()
            };

            if (ModelState.IsValid)
            {
                var files = HttpContext.Request.Form.Files;
                if (files.Count > 0)
                {

                    pelicula.Imagen = files[0];//Asignar el InforFile directamente
                }
                else
                {
                    return View(objVM);
                }
                await _repoPeliculas.ActualizarPeliculaAsync(CT.RutaPeliculasApi + pelicula.Id, pelicula, HttpContext.Session.GetString("JWToken"));
                return RedirectToAction(nameof(Index));
            }
            return View(objVM);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var status = await _repoPeliculas.BorrarAsync(CT.RutaPeliculasApi, id, HttpContext.Session.GetString("JWToken"));
            if (status)
            {
                return Json(new { success = true, message = "Borrado Correctamente" });
            }
            return Json(new { success = false, message = "Borrado Corretamente" });
        }
        [HttpGet]
        public async Task<IActionResult> GetPeliculasEnCategorias(int id)
        {
            return Json(new { data = await _repoPeliculas.GetPeliculaEnCategoriaAsync(CT.RutaPeliculasEnCategoria, id) });
        }
    }
}

Webapi/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Webapi.Models;
using Webapi.Repositorio.IRepositorio;
using Webapi.Views.Utilidades;

namespace Webapi.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {
        private readonly IUsuarioRepositorio _repoUsuario;

        public UsuariosController(IUsuarioRepositorio repoUsuario)
        {
            _repoUsuario = repoUsuario;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View(new Usuario() { });
        }
        [HttpGet]
        public async Task<IActionResult> GetTodosUsuarios()
        {
            return Json(new { data = await _repoUsuario.GetTodoAsync(CT.RutaUsuariosApi) });
        }
    }
}

Webapi/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpAcc
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Webapi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!--CSS LibreriasExternas-->
    <!--Assets agregados en el head del html-->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
     <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.5/sweetalert2.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Webapi.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-0">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Imagenes/carrete.png" class="img-fluid" width="80"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                     @if(User.Identity.IsAuthenticated)
                     {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Categorias" asp-action="Index">Categorías</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Peliculas" asp-action="Index">Peliculas</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                        </li>      
                     }                
                    </ul>

                    <!-- Para Acceso a Login Y registro-->
                    <ul class="navbar-nav">
                        @if(httpAcc.HttpContext.Session.GetString("JWToken") != null && 
                        httpAcc.HttpContext.Session.GetString("JWToken").ToString().Length > 0)
                        {
                            <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Logout">Bienvenido :@httpAcc.HttpContext.Session.GetString("Usuario") - Salir</a>
                        </li>
                        }
                        else
                        {                               
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Login">Acceder</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Registro">Registro</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Imagen de fondo a pantalla completa debajo del menu-->
        <div class="container-fluid p-0">
        <img src="~/Imagenes/cine2.jpg" class="img-fluid w-100" alt="Imagen de fondo" style="height: 50vh; object-fit: cover;">
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        <div class="container-fluid p-0">
        </div>
    </div>
    <footer class="border-top bg-dark text-white">
        <div class="container py-3">
          <p class="text-white">&copy;2025-Webapi</p>  
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--Assets JS agregados al final antes del cierre del body-->
    <!--Js plugins-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>